version: '3'
services:
  nginx:
    build: docker/nginx
    ports:
      - '8999:80'
    volumes:
      - '.:/var/www/vote/'
    environment:
      - "VIRTUAL_HOST=vote.agares.info"

  php:
    build: docker/php
    volumes:
      - '.:/var/www/vote/'