version: '3'
services:
  nginx:
    build: docker/nginx
    ports:
      - '8999:80'
    volumes:
      - '.:/var/www/vote/'
    environment:
      - "VIRTUAL_HOST=vote.agares.info"
    restart: always
    networks:
        - frontproxy_default
        - default

    networks:
        frontproxy_default:
            external: true

  php:
    build: docker/php
    volumes:
      - '.:/var/www/vote/'
    restart: always